// Generated by CoffeeScript 1.8.0
(function() {
  var config;

  config = {
    port: 3000,
    db: 'mongodb://ethan:2583832x@127.0.0.1/ethanblog'
  };

  module.exports = config;

}).call(this);

//# sourceMappingURL=config.js.map
