// Generated by CoffeeScript 1.8.0
(function() {
  var ObjectID, Schema, mongoose, replySchema;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectID = Schema.ObjectId;

  replySchema = new Schema({
    article_id: ObjectID,
    content: String,
    reply_at: {
      type: Number,
      "default": new Date().getTime()
    }
  });

  mongoose.model('Reply', replySchema);

}).call(this);

//# sourceMappingURL=reply.js.map
